services:
  - type: web
    name: your-app-name
    runtime: docker  # Or use "env: php" if not using Docker
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite  # Docker path
